/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package officeview;

import java.awt.Component;
import java.awt.Toolkit;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JViewport;

/**
 *
 * @author Mike
 */
public class ProfessorChangeScheduleDialog extends javax.swing.JDialog {

    /**
     * Creates new form ProfessorChangeScheduleDialog
     */
    public ProfessorChangeScheduleDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocation((OfficeView.screensize.width/2 - (this.getWidth()/2)), (OfficeView.screensize.height/2 - (this.getHeight()/2)));
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource(OfficeView.image)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProfessorChangeScheduleTabList = new javax.swing.JTabbedPane();
        Monday = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        MondayScrollPane = new javax.swing.JScrollPane();
        MondayInnerPanel = new javax.swing.JPanel();
        timeRange6 = new javax.swing.JPanel();
        HrInBox6 = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        MinInBox6 = new javax.swing.JComboBox();
        PeriodInBox6 = new javax.swing.JComboBox();
        jLabel30 = new javax.swing.JLabel();
        HrOutBox6 = new javax.swing.JComboBox();
        jLabel31 = new javax.swing.JLabel();
        MinOutBox6 = new javax.swing.JComboBox();
        PeriodOutBox6 = new javax.swing.JComboBox();
        jSeparator7 = new javax.swing.JSeparator();
        Tuesday = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        MondayScrollPane1 = new javax.swing.JScrollPane();
        MondayInnerPanel1 = new javax.swing.JPanel();
        timeRange7 = new javax.swing.JPanel();
        HrInBox7 = new javax.swing.JComboBox();
        jLabel32 = new javax.swing.JLabel();
        MinInBox7 = new javax.swing.JComboBox();
        PeriodInBox7 = new javax.swing.JComboBox();
        jLabel33 = new javax.swing.JLabel();
        HrOutBox7 = new javax.swing.JComboBox();
        jLabel34 = new javax.swing.JLabel();
        MinOutBox7 = new javax.swing.JComboBox();
        PeriodOutBox7 = new javax.swing.JComboBox();
        jSeparator8 = new javax.swing.JSeparator();
        Wednesday = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        MondayScrollPane2 = new javax.swing.JScrollPane();
        MondayInnerPanel2 = new javax.swing.JPanel();
        timeRange8 = new javax.swing.JPanel();
        HrInBox8 = new javax.swing.JComboBox();
        jLabel35 = new javax.swing.JLabel();
        MinInBox8 = new javax.swing.JComboBox();
        PeriodInBox8 = new javax.swing.JComboBox();
        jLabel36 = new javax.swing.JLabel();
        HrOutBox8 = new javax.swing.JComboBox();
        jLabel37 = new javax.swing.JLabel();
        MinOutBox8 = new javax.swing.JComboBox();
        PeriodOutBox8 = new javax.swing.JComboBox();
        jSeparator9 = new javax.swing.JSeparator();
        Thursday = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        MondayScrollPane3 = new javax.swing.JScrollPane();
        MondayInnerPanel3 = new javax.swing.JPanel();
        timeRange9 = new javax.swing.JPanel();
        HrInBox9 = new javax.swing.JComboBox();
        jLabel38 = new javax.swing.JLabel();
        MinInBox9 = new javax.swing.JComboBox();
        PeriodInBox9 = new javax.swing.JComboBox();
        jLabel39 = new javax.swing.JLabel();
        HrOutBox9 = new javax.swing.JComboBox();
        jLabel40 = new javax.swing.JLabel();
        MinOutBox9 = new javax.swing.JComboBox();
        PeriodOutBox9 = new javax.swing.JComboBox();
        jSeparator10 = new javax.swing.JSeparator();
        Friday = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        MondayScrollPane4 = new javax.swing.JScrollPane();
        MondayInnerPanel4 = new javax.swing.JPanel();
        timeRange10 = new javax.swing.JPanel();
        HrInBox10 = new javax.swing.JComboBox();
        jLabel41 = new javax.swing.JLabel();
        MinInBox10 = new javax.swing.JComboBox();
        PeriodInBox10 = new javax.swing.JComboBox();
        jLabel42 = new javax.swing.JLabel();
        HrOutBox10 = new javax.swing.JComboBox();
        jLabel43 = new javax.swing.JLabel();
        MinOutBox10 = new javax.swing.JComboBox();
        PeriodOutBox10 = new javax.swing.JComboBox();
        jSeparator11 = new javax.swing.JSeparator();
        UpdateButton = new javax.swing.JButton();
        AddTime = new javax.swing.JButton();
        LocationLabel = new javax.swing.JLabel();
        LocationBar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(536, 305));
        setMinimumSize(new java.awt.Dimension(536, 305));
        setModal(true);
        setPreferredSize(new java.awt.Dimension(536, 305));
        setResizable(false);

        jLabel2.setText("Time In");

        jLabel3.setText("Time Out");

        MondayScrollPane.setMaximumSize(new java.awt.Dimension(492, 32767));
        MondayScrollPane.setMinimumSize(new java.awt.Dimension(492, 22));
        MondayScrollPane.setPreferredSize(new java.awt.Dimension(492, 19));

        MondayInnerPanel.setBackground(new java.awt.Color(204, 204, 204));

        timeRange6.setBackground(new java.awt.Color(204, 204, 204));

        HrInBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        HrInBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HrInBox6ActionPerformed(evt);
            }
        });

        jLabel29.setText(":");

        MinInBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "00", "15", "30", "45" }));

        PeriodInBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "AM", "PM" }));

        jLabel30.setText("--------------to---------------");
        jLabel30.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        HrOutBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        HrOutBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HrOutBox6ActionPerformed(evt);
            }
        });

        jLabel31.setText(":");

        MinOutBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "00", "15", "30", "45" }));

        PeriodOutBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "AM", "PM" }));

        javax.swing.GroupLayout timeRange6Layout = new javax.swing.GroupLayout(timeRange6);
        timeRange6.setLayout(timeRange6Layout);
        timeRange6Layout.setHorizontalGroup(
            timeRange6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timeRange6Layout.createSequentialGroup()
                .addComponent(HrInBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MinInBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PeriodInBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(HrOutBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MinOutBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PeriodOutBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jSeparator7)
        );
        timeRange6Layout.setVerticalGroup(
            timeRange6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timeRange6Layout.createSequentialGroup()
                .addGroup(timeRange6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HrInBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(MinInBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PeriodInBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HrOutBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(MinOutBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PeriodOutBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout MondayInnerPanelLayout = new javax.swing.GroupLayout(MondayInnerPanel);
        MondayInnerPanel.setLayout(MondayInnerPanelLayout);
        MondayInnerPanelLayout.setHorizontalGroup(
            MondayInnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(timeRange6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MondayInnerPanelLayout.setVerticalGroup(
            MondayInnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MondayInnerPanelLayout.createSequentialGroup()
                .addComponent(timeRange6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 417, Short.MAX_VALUE))
        );

        MondayScrollPane.setViewportView(MondayInnerPanel);

        javax.swing.GroupLayout MondayLayout = new javax.swing.GroupLayout(Monday);
        Monday.setLayout(MondayLayout);
        MondayLayout.setHorizontalGroup(
            MondayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MondayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(116, 116, 116))
            .addComponent(MondayScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );
        MondayLayout.setVerticalGroup(
            MondayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MondayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MondayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(9, 9, 9)
                .addComponent(MondayScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
        );

        ProfessorChangeScheduleTabList.addTab("Monday", Monday);

        jLabel6.setText("Time In");

        jLabel7.setText("Time Out");

        MondayScrollPane1.setMaximumSize(new java.awt.Dimension(492, 32767));
        MondayScrollPane1.setMinimumSize(new java.awt.Dimension(492, 22));
        MondayScrollPane1.setPreferredSize(new java.awt.Dimension(492, 19));

        MondayInnerPanel1.setBackground(new java.awt.Color(204, 204, 204));

        timeRange7.setBackground(new java.awt.Color(204, 204, 204));

        HrInBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        HrInBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HrInBox7ActionPerformed(evt);
            }
        });

        jLabel32.setText(":");

        MinInBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "00", "15", "30", "45" }));

        PeriodInBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "AM", "PM" }));

        jLabel33.setText("--------------to---------------");
        jLabel33.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        HrOutBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        HrOutBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HrOutBox7ActionPerformed(evt);
            }
        });

        jLabel34.setText(":");

        MinOutBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "00", "15", "30", "45" }));

        PeriodOutBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "AM", "PM" }));

        javax.swing.GroupLayout timeRange7Layout = new javax.swing.GroupLayout(timeRange7);
        timeRange7.setLayout(timeRange7Layout);
        timeRange7Layout.setHorizontalGroup(
            timeRange7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timeRange7Layout.createSequentialGroup()
                .addComponent(HrInBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MinInBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PeriodInBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(HrOutBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MinOutBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PeriodOutBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jSeparator8)
        );
        timeRange7Layout.setVerticalGroup(
            timeRange7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timeRange7Layout.createSequentialGroup()
                .addGroup(timeRange7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HrInBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(MinInBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PeriodInBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HrOutBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(MinOutBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PeriodOutBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout MondayInnerPanel1Layout = new javax.swing.GroupLayout(MondayInnerPanel1);
        MondayInnerPanel1.setLayout(MondayInnerPanel1Layout);
        MondayInnerPanel1Layout.setHorizontalGroup(
            MondayInnerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(timeRange7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MondayInnerPanel1Layout.setVerticalGroup(
            MondayInnerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MondayInnerPanel1Layout.createSequentialGroup()
                .addComponent(timeRange7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 417, Short.MAX_VALUE))
        );

        MondayScrollPane1.setViewportView(MondayInnerPanel1);

        javax.swing.GroupLayout TuesdayLayout = new javax.swing.GroupLayout(Tuesday);
        Tuesday.setLayout(TuesdayLayout);
        TuesdayLayout.setHorizontalGroup(
            TuesdayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TuesdayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(116, 116, 116))
            .addComponent(MondayScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );
        TuesdayLayout.setVerticalGroup(
            TuesdayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TuesdayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TuesdayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(9, 9, 9)
                .addComponent(MondayScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
        );

        ProfessorChangeScheduleTabList.addTab("Tuesday", Tuesday);

        jLabel10.setText("Time In");

        jLabel11.setText("Time Out");

        MondayScrollPane2.setMaximumSize(new java.awt.Dimension(492, 32767));
        MondayScrollPane2.setMinimumSize(new java.awt.Dimension(492, 22));
        MondayScrollPane2.setPreferredSize(new java.awt.Dimension(492, 19));

        MondayInnerPanel2.setBackground(new java.awt.Color(204, 204, 204));

        timeRange8.setBackground(new java.awt.Color(204, 204, 204));

        HrInBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        HrInBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HrInBox8ActionPerformed(evt);
            }
        });

        jLabel35.setText(":");

        MinInBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "00", "15", "30", "45" }));

        PeriodInBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "AM", "PM" }));

        jLabel36.setText("--------------to---------------");
        jLabel36.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        HrOutBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        HrOutBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HrOutBox8ActionPerformed(evt);
            }
        });

        jLabel37.setText(":");

        MinOutBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "00", "15", "30", "45" }));

        PeriodOutBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "AM", "PM" }));

        javax.swing.GroupLayout timeRange8Layout = new javax.swing.GroupLayout(timeRange8);
        timeRange8.setLayout(timeRange8Layout);
        timeRange8Layout.setHorizontalGroup(
            timeRange8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timeRange8Layout.createSequentialGroup()
                .addComponent(HrInBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MinInBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PeriodInBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(HrOutBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MinOutBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PeriodOutBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jSeparator9)
        );
        timeRange8Layout.setVerticalGroup(
            timeRange8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timeRange8Layout.createSequentialGroup()
                .addGroup(timeRange8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HrInBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(MinInBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PeriodInBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HrOutBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(MinOutBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PeriodOutBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout MondayInnerPanel2Layout = new javax.swing.GroupLayout(MondayInnerPanel2);
        MondayInnerPanel2.setLayout(MondayInnerPanel2Layout);
        MondayInnerPanel2Layout.setHorizontalGroup(
            MondayInnerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(timeRange8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MondayInnerPanel2Layout.setVerticalGroup(
            MondayInnerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MondayInnerPanel2Layout.createSequentialGroup()
                .addComponent(timeRange8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 417, Short.MAX_VALUE))
        );

        MondayScrollPane2.setViewportView(MondayInnerPanel2);

        javax.swing.GroupLayout WednesdayLayout = new javax.swing.GroupLayout(Wednesday);
        Wednesday.setLayout(WednesdayLayout);
        WednesdayLayout.setHorizontalGroup(
            WednesdayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WednesdayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(116, 116, 116))
            .addComponent(MondayScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );
        WednesdayLayout.setVerticalGroup(
            WednesdayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WednesdayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WednesdayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(9, 9, 9)
                .addComponent(MondayScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
        );

        ProfessorChangeScheduleTabList.addTab("Wednesday", Wednesday);

        jLabel14.setText("Time In");

        jLabel15.setText("Time Out");

        MondayScrollPane3.setMaximumSize(new java.awt.Dimension(492, 32767));
        MondayScrollPane3.setMinimumSize(new java.awt.Dimension(492, 22));
        MondayScrollPane3.setPreferredSize(new java.awt.Dimension(492, 19));

        MondayInnerPanel3.setBackground(new java.awt.Color(204, 204, 204));

        timeRange9.setBackground(new java.awt.Color(204, 204, 204));

        HrInBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        HrInBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HrInBox9ActionPerformed(evt);
            }
        });

        jLabel38.setText(":");

        MinInBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "00", "15", "30", "45" }));

        PeriodInBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "AM", "PM" }));

        jLabel39.setText("--------------to---------------");
        jLabel39.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        HrOutBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        HrOutBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HrOutBox9ActionPerformed(evt);
            }
        });

        jLabel40.setText(":");

        MinOutBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "00", "15", "30", "45" }));

        PeriodOutBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "AM", "PM" }));

        javax.swing.GroupLayout timeRange9Layout = new javax.swing.GroupLayout(timeRange9);
        timeRange9.setLayout(timeRange9Layout);
        timeRange9Layout.setHorizontalGroup(
            timeRange9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timeRange9Layout.createSequentialGroup()
                .addComponent(HrInBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MinInBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PeriodInBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(HrOutBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MinOutBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PeriodOutBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jSeparator10)
        );
        timeRange9Layout.setVerticalGroup(
            timeRange9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timeRange9Layout.createSequentialGroup()
                .addGroup(timeRange9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HrInBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38)
                    .addComponent(MinInBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PeriodInBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HrOutBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40)
                    .addComponent(MinOutBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PeriodOutBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout MondayInnerPanel3Layout = new javax.swing.GroupLayout(MondayInnerPanel3);
        MondayInnerPanel3.setLayout(MondayInnerPanel3Layout);
        MondayInnerPanel3Layout.setHorizontalGroup(
            MondayInnerPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(timeRange9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MondayInnerPanel3Layout.setVerticalGroup(
            MondayInnerPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MondayInnerPanel3Layout.createSequentialGroup()
                .addComponent(timeRange9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 417, Short.MAX_VALUE))
        );

        MondayScrollPane3.setViewportView(MondayInnerPanel3);

        javax.swing.GroupLayout ThursdayLayout = new javax.swing.GroupLayout(Thursday);
        Thursday.setLayout(ThursdayLayout);
        ThursdayLayout.setHorizontalGroup(
            ThursdayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThursdayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(116, 116, 116))
            .addComponent(MondayScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );
        ThursdayLayout.setVerticalGroup(
            ThursdayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThursdayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ThursdayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(9, 9, 9)
                .addComponent(MondayScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
        );

        ProfessorChangeScheduleTabList.addTab("Thursday", Thursday);

        jLabel26.setText("Time In");

        jLabel27.setText("Time Out");

        MondayScrollPane4.setMaximumSize(new java.awt.Dimension(492, 32767));
        MondayScrollPane4.setMinimumSize(new java.awt.Dimension(492, 22));
        MondayScrollPane4.setPreferredSize(new java.awt.Dimension(492, 19));

        MondayInnerPanel4.setBackground(new java.awt.Color(204, 204, 204));

        timeRange10.setBackground(new java.awt.Color(204, 204, 204));

        HrInBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        HrInBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HrInBox10ActionPerformed(evt);
            }
        });

        jLabel41.setText(":");

        MinInBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "00", "15", "30", "45" }));

        PeriodInBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "AM", "PM" }));

        jLabel42.setText("--------------to---------------");
        jLabel42.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        HrOutBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        HrOutBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HrOutBox10ActionPerformed(evt);
            }
        });

        jLabel43.setText(":");

        MinOutBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "00", "15", "30", "45" }));

        PeriodOutBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "AM", "PM" }));

        javax.swing.GroupLayout timeRange10Layout = new javax.swing.GroupLayout(timeRange10);
        timeRange10.setLayout(timeRange10Layout);
        timeRange10Layout.setHorizontalGroup(
            timeRange10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timeRange10Layout.createSequentialGroup()
                .addComponent(HrInBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MinInBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PeriodInBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(HrOutBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MinOutBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PeriodOutBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jSeparator11)
        );
        timeRange10Layout.setVerticalGroup(
            timeRange10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timeRange10Layout.createSequentialGroup()
                .addGroup(timeRange10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HrInBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41)
                    .addComponent(MinInBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PeriodInBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HrOutBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43)
                    .addComponent(MinOutBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PeriodOutBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout MondayInnerPanel4Layout = new javax.swing.GroupLayout(MondayInnerPanel4);
        MondayInnerPanel4.setLayout(MondayInnerPanel4Layout);
        MondayInnerPanel4Layout.setHorizontalGroup(
            MondayInnerPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(timeRange10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MondayInnerPanel4Layout.setVerticalGroup(
            MondayInnerPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MondayInnerPanel4Layout.createSequentialGroup()
                .addComponent(timeRange10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 417, Short.MAX_VALUE))
        );

        MondayScrollPane4.setViewportView(MondayInnerPanel4);

        javax.swing.GroupLayout FridayLayout = new javax.swing.GroupLayout(Friday);
        Friday.setLayout(FridayLayout);
        FridayLayout.setHorizontalGroup(
            FridayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FridayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addGap(116, 116, 116))
            .addComponent(MondayScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );
        FridayLayout.setVerticalGroup(
            FridayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FridayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FridayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27))
                .addGap(9, 9, 9)
                .addComponent(MondayScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
        );

        ProfessorChangeScheduleTabList.addTab("Friday", Friday);

        UpdateButton.setText("Update");

        AddTime.setText("+");
        AddTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTimeActionPerformed(evt);
            }
        });

        LocationLabel.setText("Location:");

        LocationBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocationBarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LocationLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LocationBar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(AddTime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(UpdateButton))
                    .addComponent(ProfessorChangeScheduleTabList))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LocationBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LocationLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProfessorChangeScheduleTabList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddTime)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(UpdateButton)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTimeActionPerformed
        TimeRange temp = new TimeRange();
        JPanel tab = (JPanel)ProfessorChangeScheduleTabList.getSelectedComponent();
        JScrollPane scrollPane = (JScrollPane) tab.getComponent(2); 
        JViewport scrollView = (JViewport) scrollPane.getComponent(0);
        JPanel innerPanel = (JPanel) scrollView.getComponent(0);
        //for(int i=0;i<innerPanel.getComponentCount();i++){
        //    System.out.println(innerPanel.getComponent(i));
        //}
        int count = innerPanel.getComponentCount();
        innerPanel.add(temp).setLocation(0, 30 * count);
        innerPanel.validate();
    }//GEN-LAST:event_AddTimeActionPerformed

    private void LocationBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocationBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LocationBarActionPerformed

    private void HrInBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HrInBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HrInBox6ActionPerformed

    private void HrOutBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HrOutBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HrOutBox6ActionPerformed

    private void HrInBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HrInBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HrInBox7ActionPerformed

    private void HrOutBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HrOutBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HrOutBox7ActionPerformed

    private void HrInBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HrInBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HrInBox8ActionPerformed

    private void HrOutBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HrOutBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HrOutBox8ActionPerformed

    private void HrInBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HrInBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HrInBox9ActionPerformed

    private void HrOutBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HrOutBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HrOutBox9ActionPerformed

    private void HrInBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HrInBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HrInBox10ActionPerformed

    private void HrOutBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HrOutBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HrOutBox10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfessorChangeScheduleDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfessorChangeScheduleDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfessorChangeScheduleDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfessorChangeScheduleDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProfessorChangeScheduleDialog dialog = new ProfessorChangeScheduleDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddTime;
    private javax.swing.JPanel Friday;
    private javax.swing.JComboBox HrInBox;
    private javax.swing.JComboBox HrInBox1;
    private javax.swing.JComboBox HrInBox10;
    private javax.swing.JComboBox HrInBox2;
    private javax.swing.JComboBox HrInBox3;
    private javax.swing.JComboBox HrInBox4;
    private javax.swing.JComboBox HrInBox5;
    private javax.swing.JComboBox HrInBox6;
    private javax.swing.JComboBox HrInBox7;
    private javax.swing.JComboBox HrInBox8;
    private javax.swing.JComboBox HrInBox9;
    private javax.swing.JComboBox HrOutBox;
    private javax.swing.JComboBox HrOutBox1;
    private javax.swing.JComboBox HrOutBox10;
    private javax.swing.JComboBox HrOutBox2;
    private javax.swing.JComboBox HrOutBox3;
    private javax.swing.JComboBox HrOutBox4;
    private javax.swing.JComboBox HrOutBox5;
    private javax.swing.JComboBox HrOutBox6;
    private javax.swing.JComboBox HrOutBox7;
    private javax.swing.JComboBox HrOutBox8;
    private javax.swing.JComboBox HrOutBox9;
    private javax.swing.JTextField LocationBar;
    private javax.swing.JLabel LocationLabel;
    private javax.swing.JComboBox MinInBox;
    private javax.swing.JComboBox MinInBox1;
    private javax.swing.JComboBox MinInBox10;
    private javax.swing.JComboBox MinInBox2;
    private javax.swing.JComboBox MinInBox3;
    private javax.swing.JComboBox MinInBox4;
    private javax.swing.JComboBox MinInBox5;
    private javax.swing.JComboBox MinInBox6;
    private javax.swing.JComboBox MinInBox7;
    private javax.swing.JComboBox MinInBox8;
    private javax.swing.JComboBox MinInBox9;
    private javax.swing.JComboBox MinOutBox;
    private javax.swing.JComboBox MinOutBox1;
    private javax.swing.JComboBox MinOutBox10;
    private javax.swing.JComboBox MinOutBox2;
    private javax.swing.JComboBox MinOutBox3;
    private javax.swing.JComboBox MinOutBox4;
    private javax.swing.JComboBox MinOutBox5;
    private javax.swing.JComboBox MinOutBox6;
    private javax.swing.JComboBox MinOutBox7;
    private javax.swing.JComboBox MinOutBox8;
    private javax.swing.JComboBox MinOutBox9;
    private javax.swing.JPanel Monday;
    private javax.swing.JPanel MondayInnerPanel;
    private javax.swing.JPanel MondayInnerPanel1;
    private javax.swing.JPanel MondayInnerPanel2;
    private javax.swing.JPanel MondayInnerPanel3;
    private javax.swing.JPanel MondayInnerPanel4;
    private javax.swing.JScrollPane MondayScrollPane;
    private javax.swing.JScrollPane MondayScrollPane1;
    private javax.swing.JScrollPane MondayScrollPane2;
    private javax.swing.JScrollPane MondayScrollPane3;
    private javax.swing.JScrollPane MondayScrollPane4;
    private javax.swing.JComboBox PeriodInBox;
    private javax.swing.JComboBox PeriodInBox1;
    private javax.swing.JComboBox PeriodInBox10;
    private javax.swing.JComboBox PeriodInBox2;
    private javax.swing.JComboBox PeriodInBox3;
    private javax.swing.JComboBox PeriodInBox4;
    private javax.swing.JComboBox PeriodInBox5;
    private javax.swing.JComboBox PeriodInBox6;
    private javax.swing.JComboBox PeriodInBox7;
    private javax.swing.JComboBox PeriodInBox8;
    private javax.swing.JComboBox PeriodInBox9;
    private javax.swing.JComboBox PeriodOutBox;
    private javax.swing.JComboBox PeriodOutBox1;
    private javax.swing.JComboBox PeriodOutBox10;
    private javax.swing.JComboBox PeriodOutBox2;
    private javax.swing.JComboBox PeriodOutBox3;
    private javax.swing.JComboBox PeriodOutBox4;
    private javax.swing.JComboBox PeriodOutBox5;
    private javax.swing.JComboBox PeriodOutBox6;
    private javax.swing.JComboBox PeriodOutBox7;
    private javax.swing.JComboBox PeriodOutBox8;
    private javax.swing.JComboBox PeriodOutBox9;
    private javax.swing.JTabbedPane ProfessorChangeScheduleTabList;
    private javax.swing.JPanel Thursday;
    private javax.swing.JPanel Tuesday;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JPanel Wednesday;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel timeRange;
    private javax.swing.JPanel timeRange1;
    private javax.swing.JPanel timeRange10;
    private javax.swing.JPanel timeRange2;
    private javax.swing.JPanel timeRange3;
    private javax.swing.JPanel timeRange4;
    private javax.swing.JPanel timeRange5;
    private javax.swing.JPanel timeRange6;
    private javax.swing.JPanel timeRange7;
    private javax.swing.JPanel timeRange8;
    private javax.swing.JPanel timeRange9;
    // End of variables declaration//GEN-END:variables
}
