/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package officeview;

import java.awt.Color;

/**
 *
 * @author Mike
 */
public class SingleProfessorResult extends javax.swing.JPanel {

    /**private static Professor prof = OfficeView.professors.findOne("{id: #}",OfficeView.currentUserID).as(Professor.class);
     * Creates new form SingleProfessorResult
     */
    private static Professor prof = OfficeView.professors.findOne("{id: #}",OfficeView.currentUserID).as(Professor.class);
    public SingleProfessorResult() {
        initComponents();
        setVisible(true);
        setSize(getPreferredSize());
        validate();
        //jLabel6.setText("Mayday this is not a test \n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        statusIcon = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JLabel();
        locationLabel = new javax.swing.JLabel();
        locationField = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(190, 100));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        statusIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/officeview/icon3.png"))); // NOI18N
        statusIcon.setBounds(10, 10, 62, 63);
        jLayeredPane1.add(statusIcon, javax.swing.JLayeredPane.DEFAULT_LAYER);

        nameLabel.setText("Professor:");
        nameLabel.setBounds(90, 20, 50, 14);
        jLayeredPane1.add(nameLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        nameField.setText("jLabel1");
        nameField.setBounds(150, 20, 34, 14);
        jLayeredPane1.add(nameField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        locationLabel.setText("Location:");
        locationLabel.setBounds(90, 40, 44, 14);
        jLayeredPane1.add(locationLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        locationField.setText("jLabel1");
        locationField.setBounds(150, 40, 34, 14);
        jLayeredPane1.add(locationField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setMaximumSize(new java.awt.Dimension(50, 29));
        jButton2.setMinimumSize(new java.awt.Dimension(50, 29));
        jButton2.setOpaque(false);
        jButton2.setPreferredSize(new java.awt.Dimension(50, 29));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(0, 0, 190, 80);
        jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        //jButton2.setBackground(Color.yellow);
        System.out.println("test");
    }//GEN-LAST:event_jButton2MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {                                     
        //this.CurrentActiveStatus.setText("Available");
        //this.Available.setSelected(true);
        String profName = prof.getFirstName() + " " + prof.getLastName();
        String profLocation = prof.getLocation();
        this.nameLabel.setText(profName);
        this.locationLabel.setText(profLocation);
    }                                    

    public static Professor getProfessor(){
        return prof;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel locationField;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JLabel nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel statusIcon;
    // End of variables declaration//GEN-END:variables
}
